import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getDisplayName } from "next/dist/shared/lib/utils";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <ul style={{display: "flex", gap: 100}}>
            <li><Link href="/">home</Link></li>
            <li><Link href="/about">about</Link></li>
            <li><Link href="/blog">blog</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
